[VPC] Update subnets pkg
opentelekomcloud/gophertelekomcloud pull request #141
Opened 2021-04-26 16:39 UTC by lego963

### What this PR does / why we need it
Update subnets pkg

### Which issue this PR fixes
Resolves: #140

2021-04-26 19:33 UTC, anton-sidelnikov approved these changes, later dismissed

2021-04-27 07:05 UTC, outcatcher requested changes
I suppose that backward-incompatible changes are okay, as we're going to have a new version soon.

2021-04-27 07:05 UTC, outcatcher commented on openstack/networking/v1/subnets/requests.go
> +	VpcID string `json:"vpc_id"`
We should leave acronyms if possible, same we do for `VpcID`: `PrimaryDNS`, `SecondaryDNS`

2021-04-27 07:05 UTC, outcatcher commented on openstack/networking/v1/subnets/requests.go
> +	SecondaryDns  string         `json:"secondary_dns,omitempty"`
Why `Dns` but `DHCP`?

2021-04-27 08:14 UTC, anton-sidelnikov approved these changes

2021-04-27 08:17 UTC, outcatcher approved these changes

2021-04-27 08:34 UTC, merged