Add deleteWithRetry fo secgroups
opentelekomcloud/gophertelekomcloud pull request #17
Opened 2020-10-26 10:57 UTC by lego963

2020-10-26 11:04 UTC, outcatcher requested changes

2020-10-26 11:04 UTC, outcatcher commented on openstack/networking/v2/extensions/security/groups/requests.go
> +			if _, ok := err.(golangsdk.ErrDefault404); ok {
Please wait not for 404 iteration later, but for no error at all

2020-10-26 11:33 UTC, lego963 commented on openstack/compute/v2/extensions/secgroups/requests.go
> +		_, err := c.Delete(resourceURL(c, id), nil)
we don't have implementation of polling interval in `.WaitFor()` func, should I do this one?
![image](https://user-images.githubusercontent.com/17201690/97167668-44b34800-1798-11eb-84e7-aab1e3312348.png)

2020-10-26 11:47 UTC, outcatcher commented on openstack/compute/v2/extensions/secgroups/requests.go
> +		_, err := c.Delete(resourceURL(c, id), nil)
There is 1 second retry inteerval built-in into `WaitFor`, but I assume it is still too oft

2020-10-26 11:47 UTC, outcatcher commented on openstack/compute/v2/extensions/secgroups/requests.go
> +		if response.StatusCode == 202 || response.StatusCode == 204 {
No need to check those statuses, they are checked in `ProviderClient.Request`

2020-10-26 12:51 UTC, outcatcher commented on openstack/networking/v2/extensions/security/groups/requests.go
> +		return false, nil
You should return `nil` err only in case of HTTP error

2020-10-27 08:51 UTC, anton-sidelnikov approved these changes

2020-10-27 09:28 UTC, outcatcher approved these changes

2020-10-27 10:16 UTC, merged