Implement CSS snapshot configuration API
opentelekomcloud/gophertelekomcloud pull request #192
Opened 2021-06-28 13:04 UTC by outcatcher

### What this PR does / why we need it
Add `UpdateConfiguration` to CSS v1

Add acceptance tests for CSS v1 automatic snapshots configuration

### Which issue this PR fixes

Resolves #191

### Special notes for your reviewer

#### Acceptance
```
In progress...
```

2021-06-28 13:07 UTC, lego963 requested changes

2021-06-28 13:07 UTC, lego963 commented on openstack/css/v1/snapshots/requests.go
> +}
is nothing required?

2021-06-29 13:06 UTC, anton-sidelnikov approved these changes, later dismissed

2021-06-29 13:06 UTC, lego963 submitted a review, later dismissed

2021-06-29 13:40 UTC, lego963 approved these changes

2021-06-29 14:22 UTC, anton-sidelnikov approved these changes

2021-06-29 14:51 UTC, merged