[Refactor] CCE
opentelekomcloud/gophertelekomcloud pull request #409
Opened 2022-09-01 15:12 UTC by Aloento

Move all API methods and related structures to a separate file.
Inline all `Extracts` and use the `extract` package instead.
Remove all Builders

2022-09-06 16:55 UTC, Aloento commented
recheck

2022-09-07 18:42 UTC, artem-lifshits approved these changes, later dismissed

2022-09-07 18:54 UTC, Aloento commented
openstack/waf/v1 TestDomainLifecycle `Domain name a.com already exists`

2022-09-07 20:50 UTC, outcatcher requested changes

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v1/nodes/list.go
> +		strings.Join([]string{"nodes"}, "/"), nil, openstack.StdRequestOpts())
There is literally no sense in joining single-element slice :smile: 
Also, generating this URL takes two rows, it's better to move it into variable in this case:
```go
listURL := fmt.Sprintf("https://%s.%s/nodes/", clusterID, client.ResourceBaseURL()[8:]))
raw, err := client.Get(listURL, ...
```

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v1/nodes/get.go
> +	raw, err := client.Get(fmt.Sprintf("https://%s.%s", clusterID, client.ResourceBaseURL()[8:])+
Base URL for all methods should be moved to a function (I can see such in previous implementation), there is too much duplication right now.

In current implementation joining slice of predefined strings makes little sense and makes code less readable.

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v1/nodes/list.go
> +}
Would be nice to have structure documentation

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/addons/create.go
> +}
Documentation recommended.

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/addons/delete.go
> +		strings.Join([]string{"addons", id + "?cluster_id=" + clusterId}, "/"), &golangsdk.RequestOpts{
Nope, joining is an overcomplication here. Either move to a function, as it was before or use `fmt.Sprintf`

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/addons/get.go
> +		OkCodes: []int{200},
Same as previous

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/addons/list_addon_instances.go
> +		OkCodes: []int{200},
Same as previous.

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/addons/list_templates.go
> +	})
Same as previous.

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v1/nodes/update.go
> +			strings.Join([]string{"nodes", k8sName}, "/"), b, nil, &golangsdk.RequestOpts{
Same as previous.

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v1/nodes/update.go
> +			},
Maybe add some kind of `commonCCEHeaders` or `commonCCEOptions` function?

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/addons/create.go
> +		strings.Join([]string{"addons"}, "/"), b, nil, &golangsdk.RequestOpts{OkCodes: []int{201}})
See other join comments

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/addons/results.go
> +// Spec to create an addon
To match both `start with name` and `natural reading` rules, you can put it in `Spec - specification to create an add-on`

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/addons/update.go
> +		OkCodes: []int{200},
See other join comments

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/clusters/doc.go
> +		}
Should this be really changed?

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/clusters/get.go
> +		MoreHeaders: RequestOpts, JSONBody: nil,
No need to fill empty values in structures

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/clusters/testing/requests_test.go
> +	sc.ResourceBase = sc.Endpoint + "api/" + "v3/" + "projects/" + "c59fd21fd2a94963b822d8985b884673/"
Bit more readable to put it into `fmt.Sprintf`

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/nodepools/delete.go
> +		MoreHeaders: RequestOpts, JSONBody: nil,
No need to set empty/default values in structures

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/nodepools/get.go
> +		MoreHeaders: RequestOpts, JSONBody: nil,
No need to set empty/default values in structures

2022-09-07 20:50 UTC, outcatcher commented on openstack/cce/v3/nodes/testing/requests_test.go
> +
Why have you copied `ServiceClient` to several packages?
They are literally the same function, as far as I can see.

2022-09-08 08:55 UTC, closed without merging

2022-09-08 08:56 UTC, Aloento commented
Anthon-S: abot refactoring of cce. we should get rid v1 and use instead native k8s api