[Refactor] CSBS
opentelekomcloud/gophertelekomcloud pull request #423
Opened 2022-09-14 07:31 UTC by Aloento

Move all API methods and related structures to a separate file.
Inline all `Extracts` and use the `extract` package instead.
Remove all Builders

2022-11-02 11:15 UTC, Aloento commented
@anton-sidelnikov @artem-lifshits please review this thank you

2022-11-10 20:51 UTC, anton-sidelnikov requested changes

2022-11-10 20:51 UTC, anton-sidelnikov commented on openstack/csbs/v1/backup/results.go
> +const ProviderID = "fc4d5750-22e7-4798-8a46-f48f62c4c1da"
i think you can remove that

2022-11-10 20:51 UTC, anton-sidelnikov commented on openstack/csbs/v1/policies/requests.go
>  package policies
this filename misleading, maybe combine it with results in one file?

2022-11-10 20:57 UTC, Aloento commented on openstack/csbs/v1/backup/results.go
> +const ProviderID = "fc4d5750-22e7-4798-8a46-f48f62c4c1da"
no, still using

2022-11-11 09:47 UTC, Aloento commented
recheck

2022-11-11 11:21 UTC, Aloento commented
recheck

2022-11-11 19:32 UTC, Aloento commented
recheck

2022-11-14 15:13 UTC, anton-sidelnikov commented on openstack/csbs/v1/backup/results.go
> +const ProviderID = "fc4d5750-22e7-4798-8a46-f48f62c4c1da"
omg, this is hardcoded value?

2022-11-14 15:14 UTC, Aloento commented on openstack/csbs/v1/backup/results.go
> +const ProviderID = "fc4d5750-22e7-4798-8a46-f48f62c4c1da"
it is

2022-11-14 15:14 UTC, Aloento commented on openstack/csbs/v1/policies/requests.go
>  package policies
done

2022-11-14 16:44 UTC, anton-sidelnikov approved these changes

2022-11-14 16:45 UTC, Aloento commented
@artem-lifshits @Polina-Gubina

2022-11-14 16:45 UTC, Aloento commented
recheck

2022-11-16 12:13 UTC, Aloento commented
@artem-lifshits @Polina-Gubina please check thanks

2023-01-30 12:21 UTC, artem-lifshits approved these changes

2023-01-30 12:30 UTC, merged