[Refactor] CTS
opentelekomcloud/gophertelekomcloud pull request #427
Opened 2022-09-15 09:17 UTC by Aloento

Move all API methods and related structures to a separate file.
Inline all `Extracts` and use the `extract` package instead.
Remove all Builders

fix #422

2022-10-13 16:44 UTC, anton-sidelnikov commented on openstack/cts/v1/tracker/results.go
> +	Id                            string `json:"id"`
is it possible to add doc here?

2022-10-13 16:45 UTC, anton-sidelnikov requested changes

2022-10-13 16:45 UTC, anton-sidelnikov commented on openstack/cts/v1/tracker/results.go
> +	ProjectId                     string `json:"project_id"`
is it possible to add doc here?

2022-10-13 16:47 UTC, Aloento commented on openstack/cts/v1/tracker/results.go
> +	ProjectId                     string `json:"project_id"`
I couldn't find any documentation related to them, but they actually exist.

2022-11-02 11:15 UTC, Aloento commented
@anton-sidelnikov @artem-lifshits please review this thank you

2022-11-10 18:21 UTC, anton-sidelnikov requested changes
Please add tests for keyevent

2022-11-10 18:21 UTC, anton-sidelnikov commented on acceptance/openstack/cts/v1/trackers_test.go
> +		err := tracker.Delete(client)
this is really works? it should delete by name: DELETE /v1.0/{project_id}/tracker?tracker_name=system

2022-11-10 18:21 UTC, anton-sidelnikov commented on openstack/cts/v1/tracker/Delete.go
> +func Delete(client *golangsdk.ServiceClient) (err error) {
why you not passing tracker name here?

2022-11-11 17:13 UTC, anton-sidelnikov approved these changes

2022-11-11 17:14 UTC, Aloento commented
@artem-lifshits @Polina-Gubina

2022-11-11 17:16 UTC, Polina-Gubina approved these changes

2022-11-11 17:41 UTC, anton-sidelnikov commented
regate

2022-11-11 18:02 UTC, artem-lifshits approved these changes

2022-11-11 18:07 UTC, merged