[NEW] GaussDB for MySQL
opentelekomcloud/gophertelekomcloud pull request #452
Opened 2022-09-23 10:46 UTC by Aloento

fix https://github.com/opentelekomcloud/gophertelekomcloud/issues/451

2022-09-28 19:59 UTC, anton-sidelnikov requested changes
and also tests at least unit, if api not in working state

2022-09-28 19:59 UTC, anton-sidelnikov commented on openstack/gaussdb/v3/backup/CreateGaussMySqlBackup.go
> +	// 任务ID。
pls translate

2022-09-28 19:59 UTC, anton-sidelnikov commented on openstack/gaussdb/v3/backup/CreateGaussMySqlBackup.go
> +	// 	BUILDING: Backup in progress
unicode symbols, pls remove

2022-09-28 19:59 UTC, anton-sidelnikov commented on openstack/gaussdb/v3/instance/ChangeGaussMySqlInstanceSpecification.go
> +	// 	true: The order will be automatically paid from your account. The default value is true.
unicode symbols

2022-09-28 19:59 UTC, anton-sidelnikov commented on openstack/gaussdb/v3/instance/DeleteGaussMySqlInstance.go
> +	return extraJob(err, raw)
again maybe better not return task id, but wait for completion

2022-09-28 19:59 UTC, anton-sidelnikov commented on openstack/gaussdb/v3/instance/DeleteGaussMySqlReadonlyNode.go
> +	return extraJob(err, raw)
and here

2022-09-28 19:59 UTC, anton-sidelnikov commented on openstack/gaussdb/v3/instance/UpdateGaussMySqlInstanceName.go
> +	return extraJob(err, raw)
and here

2023-09-20 09:00 UTC, artem-lifshits approved these changes

2023-09-20 09:18 UTC, anton-sidelnikov approved these changes

2023-09-20 09:28 UTC, merged