[NEW] GaussDB for NoSQL
opentelekomcloud/gophertelekomcloud pull request #453
Opened 2022-09-23 11:15 UTC by Aloento

fix https://github.com/opentelekomcloud/gophertelekomcloud/issues/443

2022-09-28 19:54 UTC, anton-sidelnikov requested changes
it least need to add some unit lifecycle test

2022-09-28 19:54 UTC, anton-sidelnikov commented on openstack/gaussdbnosql/v3/ListFlavors.go
> +	// 	geminidb.cassandra indicates GaussDB(for Cassandra).
this strange ? symbols, can you remove it? it can cause some lint issues in future

2022-09-28 19:54 UTC, anton-sidelnikov commented on openstack/gaussdbnosql/v3/ListSlowLogs.go
> +	// 	SELECT
"?" again

2022-09-28 19:54 UTC, anton-sidelnikov commented on openstack/gaussdbnosql/v3/apiversion/ShowApiVersion.go
> +package apiversion
we really need show for api version? maybe list is enough?

2022-09-28 19:54 UTC, anton-sidelnikov commented on openstack/gaussdbnosql/v3/instance/CreateInstance.go
> +	// 	The value "0" indicates that SSL is disabled by default.
and here "?"

2022-09-28 19:54 UTC, anton-sidelnikov commented on openstack/gaussdbnosql/v3/instance/DeleteInstance.go
> +func extraJob(err error, raw *http.Response) (string, error) {
maybe add wait function if job id is returned? and not return exact jobid from delete, just nil as usual

2022-09-28 19:54 UTC, anton-sidelnikov commented on openstack/gaussdbnosql/v3/instance/ExpandInstanceNode.go
> +func ExpandInstanceNode(client *golangsdk.ServiceClient, opts ExpandInstanceNodeOpts) (string, error) {
and here, wait for expand to complete

2022-09-28 19:54 UTC, anton-sidelnikov commented on openstack/gaussdbnosql/v3/instance/ListInstances.go
> +	// 	normal: indicates that the instance is running properly.
again this symbols

2022-09-28 19:54 UTC, anton-sidelnikov commented on openstack/gaussdbnosql/v3/instance/ResizeInstance.go
> +	return extraJob(err, raw)
also wait?

2022-09-28 19:54 UTC, anton-sidelnikov commented on openstack/gaussdbnosql/v3/instance/ResizeInstanceVolume.go
> +	return extraJob(err, raw)
wait?

2022-09-28 19:54 UTC, anton-sidelnikov commented on openstack/gaussdbnosql/v3/instance/ShrinkInstanceNode.go
> +	// 	Either num or node_list must be set.
again this symbol

2022-09-28 20:06 UTC, artem-lifshits commented on openstack/gaussdbnosql/v3/ListDatastores.go
> +func ListDatastores(client *golangsdk.ServiceClient, datastoreName string) ([]string, error) {
It uses single page listing right?

2022-09-28 20:08 UTC, Aloento commented on openstack/gaussdbnosql/v3/ListDatastores.go
> +func ListDatastores(client *golangsdk.ServiceClient, datastoreName string) ([]string, error) {
Yes, no multiple pages

2025-11-07 10:43 UTC, anton-sidelnikov commented
TaurusDB implementes instead of Gauss

2025-11-07 10:43 UTC, closed without merging