[CES] AlarmEvent API Update
opentelekomcloud/gophertelekomcloud pull request #461
Opened 2022-10-24 08:48 UTC by Aloento

fix https://github.com/opentelekomcloud/gophertelekomcloud/issues/434

2022-10-26 17:52 UTC, anton-sidelnikov requested changes
Where is the tests?

2023-01-03 15:25 UTC, anton-sidelnikov requested changes

2023-01-03 15:25 UTC, anton-sidelnikov commented on acceptance/openstack/ces/v1/events_test.go
> +	eventsRes, err := events.ListEvents(client, events.ListEventsOpts{
Fails with: Failure in events_test.go, line 18: unexpected error "Resource not found: [GET https://ces.eu-ch2.sc.otc.t-systems.com/V1.0/b4372bf357a54745b311a8bca742feed/event], error message: {\"error_msg\":\"The API does not exist or has not been published in the environment\",\"error_code\":\"APIGW.0101\",\"request_id\":\"63373c12d550d1661dc069c496f34e52\"}\n"

2023-01-16 10:31 UTC, artem-lifshits reviewed
Hello @Aloento would be nice to get this module done :)
We have 2 issues on terraform side regarding CES

2023-01-16 10:33 UTC, Aloento commented
@artem-lifshits can you give me the issues link? thx.

2023-01-16 13:10 UTC, artem-lifshits requested changes

2023-01-16 13:10 UTC, artem-lifshits commented on acceptance/openstack/ces/v1/events_test.go
> +func TestEvents(t *testing.T) {
`CreateEvents` test missing

2023-01-16 13:54 UTC, artem-lifshits approved these changes, later dismissed

2023-01-16 15:12 UTC, anton-sidelnikov approved these changes, later dismissed

2023-01-16 15:32 UTC, artem-lifshits approved these changes

2023-01-17 14:07 UTC, anton-sidelnikov approved these changes

2023-01-17 14:16 UTC, merged