[EVS] V2 API Update
opentelekomcloud/gophertelekomcloud pull request #466
Opened 2022-11-02 11:40 UTC by Aloento

fix #429

2022-11-09 12:00 UTC, Aloento commented
recheck

2023-01-03 12:12 UTC, anton-sidelnikov requested changes

2023-01-03 12:12 UTC, anton-sidelnikov commented on acceptance/openstack/evs/v3/extensions/schedulerhints_test.go
> +	volume1, err := volumes.Create(client, createOpts)
AZ is required parameter for disk: AZ shouldn't be '' or If the AZ does not exist, the disk will fail to create.

2023-01-03 12:12 UTC, anton-sidelnikov commented on acceptance/openstack/evs/v3/extensions/schedulerstats_test.go
> +	allStats, err := schedulerstats.List(blockClient, listOpts)
The API does not exist or has not been published in the environment

2023-01-03 12:12 UTC, anton-sidelnikov commented on acceptance/openstack/evs/v3/extensions/services_test.go
> +	allServices, err := services2.List(blockClient, services2.ListOpts{})
The API does not exist or has not been published in the environment

2023-01-03 12:12 UTC, anton-sidelnikov commented on acceptance/openstack/evs/v3/extensions/volumeactions_test.go
> +	volume, err := blockstorageV3.CreateVolume(t, blockClient)
Invalid input received: Availability zone '' is invalid.

2023-01-03 12:12 UTC, anton-sidelnikov commented on acceptance/openstack/compute/v2/helper.go
> +	imageID, err := images.IDFromName(client, "Standard_Debian_10_latest")
this request fails by timeout

2023-01-03 12:12 UTC, anton-sidelnikov commented on acceptance/openstack/evs/v3/extensions/volumeactions_test.go
> +	server, err := compute.CreateServer(t, computeClient)
fails on image selection

2023-01-03 12:12 UTC, anton-sidelnikov commented on acceptance/openstack/evs/v3/extensions/volumetenants_test.go
> +	err = volumes.ExtractVolumesInto(allPages, &allVolumes)
why extract still here: panic: interface conversion: interface {} is nil, not []interface {}

2023-01-03 12:12 UTC, anton-sidelnikov commented on acceptance/openstack/evs/v3/snapshots_test.go
> +	volume1, err := CreateVolume(t, client)
same as above: Invalid input received: Availability zone '' is invalid.

2023-01-03 12:12 UTC, anton-sidelnikov commented on acceptance/openstack/evs/v3/volumes_test.go
> +	volume2, err := CreateVolume(t, client)
Same: Invalid input received: Availability zone '' is invalid.

2023-01-03 12:12 UTC, anton-sidelnikov commented on openstack/evs/extensions/volumeactions/results.go
> +func (r UploadImageResult) Extract() (VolumeImage, error) {
why old format here with extract?

2023-01-03 12:12 UTC, anton-sidelnikov commented on openstack/evs/v2/tags/requests.go
> +	_, r.Err = client.Put(client.ServiceURL("os-vendor-tags", resource_type, resource_id), b, &r.Body, &golangsdk.RequestOpts{OkCodes: []int{200}})
again old format requests.go

2023-01-03 12:12 UTC, anton-sidelnikov commented on openstack/evs/v3/volumes/results.go
move it to another file or change name

2023-01-04 11:47 UTC, Aloento commented on openstack/evs/v2/tags/requests.go
> +	_, r.Err = client.Put(client.ServiceURL("os-vendor-tags", resource_type, resource_id), b, &r.Body, &golangsdk.RequestOpts{OkCodes: []int{200}})
it's v2, not for this pr.

2023-01-04 11:47 UTC, Aloento commented on openstack/evs/extensions/volumeactions/results.go
> +func (r UploadImageResult) Extract() (VolumeImage, error) {
removed

2023-01-04 11:52 UTC, Aloento commented on acceptance/openstack/evs/v3/extensions/volumetenants_test.go
> +	err = volumes.ExtractVolumesInto(allPages, &allVolumes)
> why extract still here

LinkedPageBase still in use.

2023-01-04 16:26 UTC, Aloento commented on acceptance/openstack/evs/v3/extensions/schedulerhints_test.go
> +	volume1, err := volumes.Create(client, createOpts)
done

2023-01-04 16:29 UTC, Aloento commented on acceptance/openstack/evs/v3/extensions/schedulerstats_test.go
> +	allStats, err := schedulerstats.List(blockClient, listOpts)
skip

2023-01-04 16:32 UTC, Aloento commented on acceptance/openstack/evs/v3/extensions/services_test.go
> +	allServices, err := services2.List(blockClient, services2.ListOpts{})
skip

2023-01-04 16:35 UTC, Aloento commented on acceptance/openstack/evs/v3/extensions/volumeactions_test.go
> +	volume, err := blockstorageV3.CreateVolume(t, blockClient)
done

2023-01-04 17:02 UTC, Aloento commented on acceptance/openstack/compute/v2/helper.go
> +	imageID, err := images.IDFromName(client, "Standard_Debian_10_latest")
cannot make request images.ListDetail: server no response.
hard to fix.

2023-01-04 17:03 UTC, Aloento commented on acceptance/openstack/evs/v3/extensions/volumeactions_test.go
> +	server, err := compute.CreateServer(t, computeClient)
same above.

2023-01-04 17:13 UTC, Aloento commented on acceptance/openstack/evs/v3/volumes_test.go
> +	volume2, err := CreateVolume(t, client)
done

2023-01-04 17:14 UTC, Aloento commented on openstack/evs/v3/volumes/results.go
MV

2023-01-04 18:13 UTC, Aloento commented on acceptance/openstack/evs/v3/extensions/volumetenants_test.go
> +	err = volumes.ExtractVolumesInto(allPages, &allVolumes)
Hard to fix panic, still trying.

2023-01-04 18:13 UTC, Aloento commented on acceptance/openstack/compute/v2/helper.go
> +	imageID, err := images.IDFromName(client, "Standard_Debian_10_latest")
cannot fix now, do it in another PR.

2023-01-05 12:34 UTC, Aloento commented on acceptance/openstack/evs/v3/snapshots_test.go
> +	volume1, err := CreateVolume(t, client)
done

2026-08-21 13:22 UTC, closed without merging