[NEW] RMS
opentelekomcloud/gophertelekomcloud pull request #468
Opened 2022-11-16 12:11 UTC by Aloento

fix #438

2022-11-16 13:04 UTC, anton-sidelnikov requested changes
And tests please

2022-11-16 13:04 UTC, anton-sidelnikov commented on openstack/rms/v1/resources/ListResources.go
> +	EpId string `q:"ep_id,omitempty"`
call it EnterpriseProjectId

2022-11-16 13:04 UTC, anton-sidelnikov commented on openstack/rms/v1/resources/ListResources.go
> +	EpId string `json:"ep_id,omitempty"`
same as above

2022-11-16 13:21 UTC, gtema requested changes
please no implementation for enterpriseProjectID - this is not present/enabled in OTC - and will not be

2024-09-26 10:35 UTC, anton-sidelnikov commented
Will close it, because new service published instead of old rms

2024-09-26 10:35 UTC, closed without merging