[LTS] Refactor & API Updated
opentelekomcloud/gophertelekomcloud pull request #469
Opened 2022-11-16 13:29 UTC by Aloento

fix #428

2023-01-09 13:50 UTC, artem-lifshits submitted a review, later dismissed

2023-01-09 14:21 UTC, anton-sidelnikov approved these changes, later dismissed

2023-01-09 15:51 UTC, anton-sidelnikov approved these changes, later dismissed

2023-01-09 15:56 UTC, artem-lifshits approved these changes, later dismissed

2023-01-09 16:59 UTC, artem-lifshits requested changes

2023-01-09 16:59 UTC, artem-lifshits commented on openstack/lts/v2/transfers/DeleteTransfer.go
> +	_, err = client.Delete(client.ServiceURL("transfers")+"?log_transfer_id="+transferId, nil)
200 returned here with body:
https://docs.otc.t-systems.com/api/lts/lts_api_0030.html

2023-01-09 16:59 UTC, artem-lifshits commented on openstack/lts/v2/transfers/UpdateTransfer.go
> +	ObsEpsId string `json:"obs_eps_id,omitempty"`
Please remove `obs_eps_id`

2023-01-09 17:39 UTC, artem-lifshits requested changes

2023-01-09 17:39 UTC, artem-lifshits commented on openstack/common/pointerto/pointers.go
> +func Int32(src int32) *int32 {
But it's not even used?..

2023-01-09 17:39 UTC, artem-lifshits commented on openstack/lts/v2/streams/ListLogs.go
> +	raw, err := client.Post(client.ServiceURL("groups", opts.GroupId, "streams", opts.StreamId, "content", "query"), b, nil, nil)
Status code 200 
https://docs.otc.t-systems.com/api/lts/lts_api_0028.html

2023-01-09 17:39 UTC, artem-lifshits commented on acceptance/openstack/lts/v2/lts_test.go
> +	tools.PrintResource(t, slist)
No tests for `transfers` section

2023-01-09 17:40 UTC, artem-lifshits requested changes

2023-01-09 17:40 UTC, artem-lifshits commented on acceptance/openstack/lts/v2/lts_test.go
> +func TestLtsLifecycle(t *testing.T) {
Current test is failing:
```
=== RUN   TestLtsLifecycle
    lts_test.go:36: Failure in lts_test.go, line 36: expected 3 but got 3
    lts_test.go:28: Failure in lts_test.go, line 28: unexpected error "Bad request with: [DELETE https://lts.eu-de.otc.t-systems.com/v2/a720688fb87f4575a4c000d818061eae/groups/b629e2b1-ee94-4cdd-8f4b-0712f95a8e0c], error message: {\"error_msg\":\"Orchestration error: Invalid header parameter: Content-Type, required\",\"error_code\":\"APIGW.0106\",\"request_id\":\"aee8279c013c5ca4d784549894aaaa31\"}\n"
--- FAIL: TestLtsLifecycle (1.40s)

FAIL

Process finished with the exit code 1
```

2023-01-09 17:43 UTC, Aloento commented on openstack/common/pointerto/pointers.go
> +func Int32(src int32) *int32 {
yes hhh

2023-01-09 17:47 UTC, Aloento commented on acceptance/openstack/lts/v2/lts_test.go
> +func TestLtsLifecycle(t *testing.T) {
done

2023-01-09 17:47 UTC, Aloento commented on openstack/lts/v2/streams/ListLogs.go
> +	raw, err := client.Post(client.ServiceURL("groups", opts.GroupId, "streams", opts.StreamId, "content", "query"), b, nil, nil)
done

2023-01-09 17:48 UTC, Aloento commented on openstack/lts/v2/transfers/UpdateTransfer.go
> +	ObsEpsId string `json:"obs_eps_id,omitempty"`
done

2023-01-09 17:48 UTC, Aloento commented on openstack/lts/v2/transfers/DeleteTransfer.go
> +	_, err = client.Delete(client.ServiceURL("transfers")+"?log_transfer_id="+transferId, nil)
done

2023-01-10 09:38 UTC, artem-lifshits approved these changes

2023-01-10 09:39 UTC, anton-sidelnikov approved these changes

2023-01-10 09:47 UTC, merged