[DWS] fix for flavors list
opentelekomcloud/gophertelekomcloud pull request #495
Opened 2023-01-27 17:43 UTC by anton-sidelnikov

Wrong response without "Content-Type": "application/json" header

2023-01-27 17:45 UTC, artem-lifshits approved these changes, later dismissed

2023-01-27 17:51 UTC, artem-lifshits approved these changes, later dismissed

2023-01-28 10:59 UTC, Aloento approved these changes

2023-01-28 11:01 UTC, Aloento requested changes
openstack.StdRequestHeader() maybe

2023-01-28 13:52 UTC, anton-sidelnikov commented
> openstack.StdRequestHeader() maybe
@Aloento,
que interesante, set openstack.StdRequestOpts()

2023-01-28 14:23 UTC, Aloento approved these changes, later dismissed

2023-01-30 09:03 UTC, artem-lifshits approved these changes, later dismissed

2023-01-30 10:59 UTC, Aloento approved these changes

2023-01-30 11:00 UTC, artem-lifshits approved these changes

2023-01-30 11:10 UTC, merged

2023-02-02 09:55 UTC, bakhterets reviewed
viewed