[CSBS] Fix Test
opentelekomcloud/gophertelekomcloud pull request #497
Opened 2023-02-03 12:10 UTC by Aloento

2023-02-03 14:59 UTC, anton-sidelnikov requested changes

2023-02-03 14:59 UTC, anton-sidelnikov commented on openstack/csbs/v1/backup/testing/requests_test.go
> +	options := resource.GetResBackupOpts{CheckProtectable: []resource.ResourceCapQueryParams{
please revert

2023-02-03 15:13 UTC, Aloento commented on openstack/csbs/v1/backup/testing/requests_test.go
> +	options := resource.GetResBackupOpts{CheckProtectable: []resource.ResourceCapQueryParams{
done

2023-02-07 13:44 UTC, Aloento commented
recheck

2023-02-07 13:49 UTC, anton-sidelnikov approved these changes

2023-02-07 13:51 UTC, artem-lifshits approved these changes

2023-02-07 13:58 UTC, anton-sidelnikov commented
regate

2023-02-07 14:05 UTC, merged