ELB
opentelekomcloud/gophertelekomcloud pull request #522
Opened 2023-04-13 23:08 UTC by Aloento

fix #512

2023-07-03 08:16 UTC, anton-sidelnikov requested changes

2023-07-03 08:16 UTC, anton-sidelnikov commented on acceptance/openstack/elb/v3/ipgroups_test.go
> +	ipgroupsLists, err := ipgroups.List(client, ipgroups.ListOpts{}).AllPages()
why extract here? Previously it works without it

2023-07-03 08:16 UTC, anton-sidelnikov commented on acceptance/openstack/elb/v3/ipgroups_test.go
> +	ipGroupsSlices, err := ipgroups.List(client, ipgroups.ListOpts{}).AllPages()
extract and paging should be inside list func

2023-07-03 08:16 UTC, anton-sidelnikov commented on acceptance/openstack/elb/v3/ipgroups_test.go
> +	ipGroupsSlices, err := ipgroups.List(client, ipgroups.ListOpts{}).AllPages()
why you change that?

2023-07-03 08:16 UTC, anton-sidelnikov commented on acceptance/openstack/elb/v3/loadbalancers_test.go
>  	loadbalancerPages, err := loadbalancers.List(client, listOpts).AllPages()
extract and paging should be inside list func again

2023-07-03 08:16 UTC, anton-sidelnikov commented on acceptance/openstack/elb/v3/security_policy_test.go
> +	allPolicies, err := security_policy.ExtractSecurities(allPages)
again extract outside of the function

2023-07-04 20:29 UTC, Aloento commented on acceptance/openstack/elb/v3/ipgroups_test.go
> +	ipgroupsLists, err := ipgroups.List(client, ipgroups.ListOpts{}).AllPages()
All List API returned with pageinfo should warp with Page

https://docs.otc.t-systems.com/elastic-load-balancing/api-ref/apis_v3/ip_address_group/querying_ip_address_groups.html#:~:text=is%20automatically%20generated.-,page_info,-PageInfo%20object

2023-07-04 20:29 UTC, Aloento commented on acceptance/openstack/elb/v3/ipgroups_test.go
> +	ipGroupsSlices, err := ipgroups.List(client, ipgroups.ListOpts{}).AllPages()
same

2023-07-04 20:30 UTC, Aloento commented on acceptance/openstack/elb/v3/loadbalancers_test.go
>  	loadbalancerPages, err := loadbalancers.List(client, listOpts).AllPages()
currently no. have to change how the Page struct works.

2023-07-04 20:32 UTC, Aloento commented on acceptance/openstack/elb/v3/security_policy_test.go
> +	allPolicies, err := security_policy.ExtractSecurities(allPages)
I will try, but it is a huge modification for all functions using Page.

2025-11-07 10:43 UTC, closed without merging