add dcaas
opentelekomcloud/gophertelekomcloud pull request #546
Opened 2023-07-10 10:17 UTC by vladimirvshivkov

### What this PR does / why we need it

Adds DCaaS support

### Which issue this PR fixes

### Special notes for your reviewer

2023-07-14 15:41 UTC, anton-sidelnikov requested changes

2023-07-14 15:41 UTC, anton-sidelnikov commented on acceptance/openstack/dcaas/v2/direct_connect_endpoint_group_test.go
> +		Name:      "test-direct-connect-endpoint-group",
please use some randomization for names like:
name := strings.ToLower(tools.RandomString("direct-connect-endpoint-group-test", 5))

2023-07-14 15:41 UTC, anton-sidelnikov commented on acceptance/openstack/dcaas/v2/direct_connect_test.go
> +		Name:      "test-direct-connect",
please use some randomization for names like:
name := strings.ToLower(tools.RandomString("direct-connect-test", 5))

2023-07-14 15:41 UTC, anton-sidelnikov commented on acceptance/openstack/dcaas/v2/virtual_gateway_test.go
> +		Name:                 "test-virtual-interface",
please use some randomization for names like:
name := strings.ToLower(tools.RandomString("virtual-interface-test", 5))

2023-07-14 15:41 UTC, anton-sidelnikov commented on acceptance/openstack/dcaas/v2/virtual_gateway_test.go
> +		Name:        "test-virtual-interface-updated",
and here you can use previous name variable with strings.Join(name, "-update")

2023-07-14 15:41 UTC, anton-sidelnikov commented on acceptance/openstack/dcaas/v2/virtual_interface_test.go
> +		Name:              "test-virtual-interface",
same here

2023-07-14 15:41 UTC, anton-sidelnikov commented on openstack/dcaas/v2/dc-endpoint-group/Update.go
> +package dc_endpoint_group
no update? if yes seems you can delete this file

2023-07-14 15:41 UTC, anton-sidelnikov commented on openstack/dcaas/v2/virtual-interface/Update.go
> +package virtual_interface
and here if no update, i think better to delete empty file

2023-07-14 15:43 UTC, artem-lifshits requested changes

2023-07-14 15:43 UTC, artem-lifshits commented on acceptance/openstack/dcaas/v2/virtual_gateway_test.go
> +		VpcId:                "0bd45fdf-bf78-41e5-bd08-99f1c65e0147",
Please remove hardcoded vpc/endpoint id and take it from os envs

2023-07-14 15:43 UTC, artem-lifshits commented on acceptance/openstack/dcaas/v2/virtual_interface_test.go
> +		VgwID:             "d27d5bd2-97b3-4bd8-b7e5-189a71c14846",
same here

2023-07-14 15:43 UTC, artem-lifshits commented on openstack/dcaas/v2/dc-endpoint-group/Create.go
> +type CreateOpts struct {
Missing required `tenant_id` parameter:
https://docs.otc.t-systems.com/direct-connect/api-ref/apis/direct_connect_endpoint_group/creating_an_endpoint_group.html#en-dc-topic-0055025336
May be documentation bug, please comment

2023-07-14 15:43 UTC, artem-lifshits commented on openstack/dcaas/v2/dc-endpoint-group/List.go
> +type DCEndpointGroup struct {
Tenant id parameter missing

2023-07-14 15:43 UTC, artem-lifshits commented on openstack/dcaas/v2/dc-endpoint-group/Update.go
> +package dc_endpoint_group
Missing update method and structs

2023-07-14 15:43 UTC, artem-lifshits commented on openstack/dcaas/v2/direct-connect/Create.go
> +	var res DirectConnect
Response struct has some additional parameters (like vlan/created time).
https://docs.otc.t-systems.com/direct-connect/api-ref/apis/connection/overview.html#en-dc-topic-0055025314-en-us-topic-0070676569-table49902238182444

2023-07-14 15:43 UTC, artem-lifshits commented on openstack/dcaas/v2/direct-connect/List.go
> +func List(c *golangsdk.ServiceClient, opts ListOpts) ([]DirectConnect, error) {
Maybe use just `id string` instead of `opts ListOpts`?

2023-07-14 15:43 UTC, artem-lifshits commented on openstack/dcaas/v2/virtual-gateway/List.go
> +	RegionID           string `json:"region_id"`
For `RegionID` docu states: `This is a reserved field, which is not used currently.`
Please check if it's aligned.

2023-07-14 15:43 UTC, artem-lifshits commented on openstack/dcaas/v2/virtual-gateway/List.go
> +func List(c *golangsdk.ServiceClient, opts ListOpts) ([]VirtualGateway, error) {
Redundant struct `ListOpts`

2023-07-14 15:43 UTC, artem-lifshits commented on openstack/dcaas/v2/virtual-gateway/Update.go
> +	_, err = c.Put(c.ServiceURL("dcaas", "virtual-gateways", id), b, nil, &golangsdk.RequestOpts{
`VirtualGateway` is also returned if docu doesn't lie:
https://docs.otc.t-systems.com/direct-connect/api-ref/apis/virtual_gateway/updating_a_virtual_gateway.html#en-dc-topic-0055025326-table4284712915501

2023-07-14 15:43 UTC, artem-lifshits commented on openstack/dcaas/v2/virtual-interface/Update.go
> +package virtual_interface
empty file

2023-07-17 11:05 UTC, anton-sidelnikov approved these changes, later dismissed

2023-07-31 09:37 UTC, vladimirvshivkov commented
virtual gateway creation fails with error:

<img width="1222" alt="image" src="https://github.com/opentelekomcloud/gophertelekomcloud/assets/32225815/0a851601-6d30-4f9b-ad30-5ef2fd83b00a">

<img width="838" alt="image" src="https://github.com/opentelekomcloud/gophertelekomcloud/assets/32225815/7a5d2c85-3155-43ae-bd66-5226e0136378">

2023-07-31 13:44 UTC, anton-sidelnikov submitted a review, later dismissed

2023-08-07 09:55 UTC, artem-lifshits submitted a review, later dismissed

2023-08-07 10:24 UTC, anton-sidelnikov approved these changes, later dismissed

2023-08-18 09:09 UTC, anton-sidelnikov submitted a review, later dismissed

2023-08-18 09:38 UTC, artem-lifshits submitted a review, later dismissed

2023-08-21 08:14 UTC, anton-sidelnikov approved these changes

2023-08-21 08:45 UTC, artem-lifshits approved these changes

2023-08-21 09:06 UTC, merged