Implement CBR tasks
opentelekomcloud/gophertelekomcloud pull request #68
Opened 2020-12-08 14:08 UTC by lego963

2020-12-08 14:53 UTC, anton-sidelnikov requested changes

2020-12-08 14:53 UTC, anton-sidelnikov commented on openstack/cbr/v3/tasks/results.go
> +type OpErrorInfo struct {
can you use Operation instead of Op?

2020-12-08 22:29 UTC, outcatcher commented on acceptance/openstack/cbr/v3/tasks_test.go
> +	if err != nil {
Please use `th.AssertNoError`

2020-12-09 10:02 UTC, anton-sidelnikov approved these changes

2020-12-09 10:13 UTC, merged