[sfs_turbo] Minor refactoring
opentelekomcloud/gophertelekomcloud pull request #97
Opened 2021-02-11 10:14 UTC by lego963

### What this PR does / why we need it
Minor refactoring `sfs_turbo` package
Implement change SG action

### Which issue this PR fixes
Resolves: #96

2021-02-12 11:08 UTC, lego963 commented
recheck

2021-02-15 09:36 UTC, outcatcher requested changes

2021-02-15 09:36 UTC, outcatcher commented on openstack/compute/v2/extensions/secgroups/requests.go
> +			if _, ok := err.(golangsdk.ErrDefault400); ok {
This is not a part of SFS, please move to another PR. Also, maybe check for both 409 and 400?

2021-02-15 09:36 UTC, outcatcher commented on openstack/sfs_turbo/v1/shares/results.go
> +	return s, err
>r.ExtractInto(&s)

Address of pointer seems to be given

2021-02-15 09:44 UTC, anton-sidelnikov requested changes

2021-02-15 09:44 UTC, anton-sidelnikov commented on openstack/client.go
>  	return initClientOpts(client, eo, "sharev2")
const = (
sharev2
sfsturbo
)

2021-02-15 09:54 UTC, lego963 commented on openstack/client.go
>  	return initClientOpts(client, eo, "sharev2")
We don't reuse these strings

2021-02-15 10:06 UTC, outcatcher approved these changes

2021-02-15 10:13 UTC, lego963 commented
recheck

2021-02-15 10:15 UTC, anton-sidelnikov approved these changes

2021-02-15 10:30 UTC, merged